spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: ${MYSQL_PASSWORD}
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
  jackson:
    property-naming-strategy: SNAKE_CASE
  jpa:
    generate-ddl: false
    show-sql: false
    open-in-view: false
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    password: ${REDIS_PASSWORD}
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_ADDRESS}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
auth:
  jwt:
    access-exp: ${JWT_EXP_ACCESS}
    refresh-exp: ${JWT_EXP_REFRESH}
    secret: ${JWT_SECRET_KEY}
cloud:
  aws:
    s3:
      bucket: ${AWS_BUCKET}
    region:
      static: ${AWS_REGION}
    stack:
      auto: false
    credentials:
      instanceProfile: true
      accessKey: ${AWS_ACCESS}
      secretKey: ${AWS_SECRET}