name: DockerHub Upload

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: '17'
          java-package: jdk

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        shell: bash

      - name: Build
        run: ./gradlew build
        shell: bash

      - name: Docker Login
        uses: docker/login-action@v1.10.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Docker Image Build
        run: docker build -t dohyeon5626/today-todolist .

      - name: Upload to DockerHub
        run: docker push dohyeon5626/today-todolist
